<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="fb_test" Id="{b52271f6-142e-4284-8dab-062fe243e4d2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fb_test
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="fb_test">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>